server:
  port: 8083
#数据库连接:注意要加上时区
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#配置mapper.xml文件存放路径
mybatis:
  mapper-locations: classpath:mapper/*.xml